"""Added transaction, currency and tag tables.

Revision ID: bcfb32a9b521
Revises: 71b1d42786e8
Create Date: 2023-11-22 17:42:39.156793
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bcfb32a9b521'
down_revision: Union[str, None] = '71b1d42786e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'currency',
        sa.Column('name', sa.String(length=5), nullable=False),
        sa.Column('exchange_rate_to_nominate_currency', sa.Float(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'tag',
        sa.Column('tag', sa.String(length=15), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tag'),
    )
    op.create_table(
        'transaction',
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency_id', sa.Integer(), nullable=False),
        sa.Column('is_income', sa.Boolean(), nullable=False),
        sa.Column('comment', sa.String(length=256), nullable=True),
        sa.Column('date', sa.Date(), server_default=sa.text('now()'), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['currency_id'], ['currency.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'transaction_tag_association',
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tag_id'], ['tag.id']),
        sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id']),
        sa.PrimaryKeyConstraint('transaction_id', 'tag_id'),
    )
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('transaction_tag_association')
    op.drop_table('transaction')
    op.drop_table('tag')
    op.drop_table('currency')
    # ### end Alembic commands ###
